### ISSUE TITLE
Textures appear to be reversed top-to-bottom

### ISSUE THREAD

**Issue by TimAidley** [octo-code/webp-unity3d#10]
I have this running on OSX, and when I use it to load a webp texture, the texture appears to be reversed, top-to-bottom. Give me a shout if you need an image that exhibits this behaviour.

**Comment by timleader** [comment]
Unfortunately I have not yet been able to test support on OSX as I don't currently have an OSX machine, However if you can send me a copy of the WebP texture, I will certainly look into this as much as I can.

**Comment by TimAidley** [comment]
Hi Tim,
  thanks for getting back to me. I've attached one of the textures - I
didn't want to attach it on github as it's from our game and shouldn't
really be publicly available.

Cheers,

Tim

**Comment by timleader** [comment]
I've just pushed an update that should fix this issue, I've tested it my end and it seems to work. Let me know if this fix works for you. 

PS. I haven't had time to look at if the encoding is doing the flipping too, so this issue may be present there too.

**Comment by TimAidley** [comment]
Thanks Tim; I'll check it out.

I'm not currently using the code for encoding, so I wouldn't be able to
help you there!

Cheers,

Tim

**Comment by TimAidley** [comment]
Hi Tim, yeah, that worked for me. Thanks for the fix!
