### ISSUE TITLE
ios android Can work?

### ISSUE THREAD

**Issue by zynbasil** [octo-code/webp-unity3d#9]
I need webp work on ios & android.
how can i make this work?

**Comment by zynbasil** [comment]
android is first~

**Comment by zynbasil** [comment]
tk~

**Comment by zynbasil** [comment]
In unity3d I download and run the scene Test (unity3d 4.6)

DllNotFoundException: libwebp
WebP.Texture2DExt.CreateTexture2DFromWebP (System.Byte[] lData, Boolean lMipmaps, Boolean lLinear, WebP.Error& lError)
WebPTest.Start () (at Assets/Example/Scripts/WebPTest.cs:27)

help~~!!!

**Comment by boboshu** [comment]
i want to use on IOS and android too!

**Comment by timleader** [comment]
@zynbasil your Exception suggests either the libwebp.dll file is missing or possibly can't be seen by Unity3D for some reason, can you confirm the following:

- libwebp.dll is present in 'Plugins/x86' 
- your Unity3D Editor is not in WebPlayer mode (WebPlayer mode isn't compatible with native code).
- you have an active Unity Pro license (native code I don't believe works in the Unity Editor under the Free License, however native code will work on Android and iOS under the Free license, I am currently looking into a solution for this).

**Comment by zynbasil** [comment]
android ios can work?

**Comment by zynbasil** [comment]
In WebPlayer mode 

Assets/Example/Scripts/WebPTest.cs(25,30): error CS0117: `System.IO.File' does not contain a definition for `ReadAllBytes'

help~~~

**Comment by timleader** [comment]
Under a Unity3D Free License Android and iOS is supported, however the Unity3D Editor (PC) itself won't be supported.

Under a Unity3D Pro License Android, iOS and PC is supported and the Unity3D Editor (PC) itself will also work.

Please note: 
I don't have a OSX machine myself so I have not been able to add support for Unity3D Editor (OSX) as of yet, though this will be coming soon.

**Comment by zynbasil** [comment]
Under Unity3D Pro License,  you mean Android IOS PC webp-unity3d will work?

May be you can post a ios project example~ Thank you~ (or android project) 

More ReadMe Content please~

**Comment by timleader** [comment]
That is indeed what I meant, I will have a look into this, but the unity3d project in the unity folder is meant to build straight to android and has done a number of times on my machine. 

Unfortunately this project is still underdevelopment and there is still numerous things that need adding. Though I will try to add a more comprehensive readme soon.

**Comment by zynbasil** [comment]
Thank You~
